{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "939fedf4-db39-4b84-b022-933a0de2c0dd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: plotly in c:\\users\\rdm12\\anaconda3\\lib\\site-packages (5.24.1)\n",
      "Requirement already satisfied: tenacity>=6.2.0 in c:\\users\\rdm12\\anaconda3\\lib\\site-packages (from plotly) (9.0.0)\n",
      "Requirement already satisfied: packaging in c:\\users\\rdm12\\anaconda3\\lib\\site-packages (from plotly) (24.2)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install plotly"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "36fd1977-c80d-4785-97d6-82d915d60601",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2026-02-18 12:18:05.185 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "C:\\Users\\rdm12\\anaconda3\\Lib\\site-packages\\keras\\src\\saving\\saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 10 variables whereas the saved optimizer has 18 variables. \n",
      "  saveable.load_own_variables(weights_store.get(inner_path))\n",
      "2026-02-18 12:18:05.414 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.571 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\rdm12\\anaconda3\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2026-02-18 12:18:06.572 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.574 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.575 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.576 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.578 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.581 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.583 Session state does not function when running a script without `streamlit run`\n",
      "2026-02-18 12:18:06.584 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.588 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.590 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.593 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.594 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.597 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.598 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.606 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.614 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.616 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.619 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.621 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.624 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.626 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.628 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.630 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.633 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.636 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.640 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.642 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.645 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.648 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.650 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.652 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.654 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.656 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.657 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.661 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.664 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.665 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.670 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.674 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.675 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.676 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.678 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.679 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2026-02-18 12:18:06.683 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import joblib\n",
    "import plotly.graph_objects as go\n",
    "from tensorflow.keras.models import load_model\n",
    "\n",
    "\n",
    "\n",
    "# Page config\n",
    "st.set_page_config(page_title=\"Battery Failure Predictor\", layout=\"centered\")\n",
    "\n",
    "# Load assets\n",
    "model = load_model(\"battery_failure_ann_model.keras\")\n",
    "scaler = joblib.load(\"scaler.pkl\")\n",
    "\n",
    "# Styling\n",
    "st.markdown(\n",
    "    \"\"\"\n",
    "    <style>\n",
    "    .main {padding-top: 20px;}\n",
    "    .stButton button {width: 100%;}\n",
    "    </style>\n",
    "    \"\"\",\n",
    "    unsafe_allow_html=True\n",
    ")\n",
    "\n",
    "st.title(\"EV Battery Failure Prediction\")\n",
    "\n",
    "st.write(\"Provide battery parameters to estimate failure probability.\")\n",
    "\n",
    "# Inputs\n",
    "charge_cycles = st.number_input(\"Charge Cycles\", min_value=0, value=500)\n",
    "avg_temperature = st.number_input(\"Average Temperature (°C)\", value=35.0)\n",
    "depth_of_discharge = st.number_input(\"Depth of Discharge (%)\", value=60.0)\n",
    "fast_charge_ratio = st.number_input(\"Fast Charge Ratio (0–1)\", min_value=0.0, max_value=1.0, value=0.3)\n",
    "age_months = st.number_input(\"Battery Age (Months)\", min_value=0, value=12)\n",
    "\n",
    "# Prediction button\n",
    "if st.button(\"Predict Failure Risk\"):\n",
    "\n",
    "    input_data = np.array([[\n",
    "        charge_cycles,\n",
    "        avg_temperature,\n",
    "        depth_of_discharge,\n",
    "        fast_charge_ratio,\n",
    "        age_months\n",
    "    ]])\n",
    "\n",
    "    input_scaled = scaler.transform(input_data)\n",
    "\n",
    "    prediction_prob = model.predict(input_scaled)[0][0]\n",
    "    prediction_class = int(prediction_prob > 0.5)\n",
    "\n",
    "    st.subheader(\"Prediction Result\")\n",
    "\n",
    "    st.write(f\"Failure Probability: {prediction_prob:.2f}\")\n",
    "\n",
    "    # Confidence calculation (distance from decision boundary)\n",
    "    confidence = abs(prediction_prob - 0.5) * 2\n",
    "    st.write(f\"Model Confidence: {confidence:.2f}\")\n",
    "\n",
    "    if prediction_class == 1:\n",
    "        st.error(\"Battery Failure Likely\")\n",
    "    else:\n",
    "        st.success(\"Battery Condition Normal\")\n",
    "\n",
    "    # Gauge meter\n",
    "    fig = go.Figure(go.Indicator(\n",
    "        mode=\"gauge+number\",\n",
    "        value=float(prediction_prob * 100),\n",
    "        title={'text': \"Failure Risk (%)\"},\n",
    "        gauge={\n",
    "            'axis': {'range': [0, 100]},\n",
    "            'bar': {'thickness': 0.3},\n",
    "            'steps': [\n",
    "                {'range': [0, 40], 'label': 'Low'},\n",
    "                {'range': [40, 70], 'label': 'Medium'},\n",
    "                {'range': [70, 100], 'label': 'High'}\n",
    "            ]\n",
    "        }\n",
    "    ))\n",
    "\n",
    "    st.plotly_chart(fig)\n",
    "\n",
    "# -------------------------\n",
    "# Batch Prediction Section\n",
    "# -------------------------\n",
    "\n",
    "st.divider()\n",
    "st.subheader(\"Batch Prediction from CSV\")\n",
    "\n",
    "uploaded_file = st.file_uploader(\"Upload CSV File\", type=[\"csv\"])\n",
    "\n",
    "if uploaded_file is not None:\n",
    "\n",
    "    batch_df = pd.read_csv(uploaded_file)\n",
    "\n",
    "    st.write(\"Preview of Uploaded Data:\")\n",
    "    st.dataframe(batch_df.head())\n",
    "\n",
    "    if st.button(\"Run Batch Prediction\"):\n",
    "\n",
    "        batch_scaled = scaler.transform(batch_df)\n",
    "        batch_probs = model.predict(batch_scaled)\n",
    "\n",
    "        batch_df[\"failure_probability\"] = batch_probs\n",
    "        batch_df[\"predicted_class\"] = (batch_probs > 0.5).astype(int)\n",
    "\n",
    "        st.write(\"Prediction Results:\")\n",
    "        st.dataframe(batch_df)\n",
    "\n",
    "        csv = batch_df.to_csv(index=False).encode(\"utf-8\")\n",
    "        st.download_button(\n",
    "            \"Download Results CSV\",\n",
    "            csv,\n",
    "            \"predictions.csv\",\n",
    "            \"text/csv\"\n",
    "        )\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "9786a12d-cc23-43a4-a984-de20f6321e8c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
